services:
  ollama:
    image: ghcr.io/ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6g
          cpus: '2'
    networks:
      - shared-network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - "OLLAMA_BASE_URL=http://ollama:11434"
      - "OLLAMA_STREAM=true"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./open-webui:/app/backend/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1.5g
          cpus: '1'
    networks:
      - shared-network

networks:
  shared-network:
    external: true
